config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root "home#index"
  get "up" => "rails/health#show", as: :rails_health_check
  get '/articles' => "articles#index"
  get '/articles/new' => "articles#new", as: 'new_article'
  post '/articles' => "articles#create", as: 'create_article'
  get '/articles/:id' => "articles#show", as: 'article'
  get '/articles/:id/edit' => "articles#edit", as: 'edit_article'
  put "articles/:id" => "articles#update", as: "update_article" # update_article_path(article.id)
  patch "articles/:id" => "articles#update"
  delete "articles/:id" => "articles#delete", as: "delete_article" 

  get '/user_profiles' => "user_profiles#index"
  get '/user_profiles/new' => "user_profiles#new", as: 'new_user_profiles'
  post '/user_profiles' => "user_profiles#create", as: 'create_user_profile'
  get '/user_profiles/:id' => "user_profiles#show", as: 'user_profile'
  get '/user_profiles/:id/edit' => "user_profiles#edit", as: 'edit_user_profile'
  put "user_profiles/:id" => "user_profiles#update", as: "update_user_profile" # update_user_profile_path(user_profile.id)
  patch "user_profiles/:id" => "user_profiles#update"
  delete "user_profiles/:id" => "user_profiles#delete", as: "delete_user_profile" 

  get '/comments' => "comments#index"
  get '/comments/new' => "comments#new", as: 'new_comments'
  post '/comments' => "comments#create", as: 'create_comment'
  get '/comments/:id' => "comments#show", as: 'comment'
  get '/comments/:id/edit' => "comments#edit", as: "edit_comment"
  put "comments/:id" => "comments#update", as: "update_comment" # update_path_path(comment.id)
  patch "comments/:id" => "comments#update"
  delete "comments/:id" => "comments#delete", as: "delete_comment"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.order(:id)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    
    if @article.save
      redirect_to articles_path
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to articles_path
    else
      render :edit
    end
  end

  def delete
    @article = Article.find(params[:id])
    @article.delete
    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:name, :body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to comments_path
    else
      render :new
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to comments_path
    else
      render :edit
    end
  end

  def delete
    @comment = Comment.find(params[:id])
    @comment.delete
    redirect_to comments_path
  end

  private
  def comment_params
    params.require(:comment).permit(:name, :comments)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  require "bcrypt"
  def index
    @user_profiles = UserProfile.all
  end

  def show
    @user_profile = UserProfile.find(params[:id])
  end

  def new
    @user_profile = UserProfile.new
  end

  def create
    @user_profile = UserProfile.new(user_profile_params)

    if @user_profile.save
      redirect_to user_profiles_path
    else
      render :new
    end
  end

  def edit
    @user_profile = UserProfile.find(params[:id])
  end

  def update
    @user_profile = UserProfile.find(params[:id])
    if @user_profile.update(user_profile_params)
      redirect_to user_profiles_path
    else
      render :edit
    end
  end

  def delete
    @user_profile = UserProfile.find(params[:id])
    @user_profile.delete
    redirect_to user_profiles_path
  end

  private
  def user_profile_params
    params.require(:user_profile).permit(:fullname, :username, :password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/articles/edit.html.erb
<%= form_with scope: :article, url: update_article_path(@article.id), method: :put, local: true do |f| %>

<p>
  <% if @article.errors.any? %>
    <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</p>

<p>
  <%= f.label :body %><br/>
  <%= f.text_field :body %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/articles/index.html.erb
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Body</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Delete</th>
      <th><%= link_to 'New Article', new_article_path  %></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.id %> </td>
        <td><%= article.name %> </td>
        <td><%= article.body %> </td>
        <td><%= link_to 'Show', article_path(article.id) %> </td>
        <td><%= link_to 'Edit', edit_article_path(article.id) %> </td>
        <td><%= button_to 'Delete', delete_article_path(article.id), method: :delete %> </td>
      </tr>
    <% end %>
  </tbody>
</table>


app/views/articles/new.html.erb
<%= form_with scope: :article, url: create_article_path, local: true do |f| %>

<p>
  <% if @article.errors.any? %>
    <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</p>

<p>
  <%= f.label :name %><br/>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :body %><br/>
  <%= f.text_field :body %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/articles/show.html.erb
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Body</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @article.id %> </td>
        <td><%= @article.name %> </td>
        <td><%= @article.body %> </td>
      </tr>
  </tbody>
</table>


app/views/comments/edit.html.erb
<%= form_with scope: :comment, url: update_comment_path(@comment.id), method: :put, local: true do |f| %>

<p>
  <% if @comment.errors.any? %>
    <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</p>

<p>
  <%= f.label :comments %><br/>
  <%= f.text_field :comments %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/comments/index.html.erb
<table>
  <thead>
    <tr>
      <th>Posted by-</th>
      <th>Comment</th>   
      <th>Edit</th>
      <th>Delete</th>   
      <th><%= link_to 'Add New Comment', new_comments_path  %></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %> </td>
        <td><%= comment.comments %> </td>
        <td><%= link_to 'Edit', edit_comment_path(comment.id) %> </td>
        <td><%= button_to 'Delete', delete_comment_path(comment.id), method: :delete %> </td>
      </tr>
    <% end %>
  </tbody>
</table>


app/views/comments/new.html.erb
<%= form_with scope: :comment, url: create_comment_path, local: true do |f| %>

<p>
  <% if @comment.errors.any? %>
    <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</p>

<p>
  <%= f.label :name %><br/>
  <%= f.text_field :name %>
</p>


<p>
  <%= f.label :comments %><br/>
  <%= f.text_field :comments %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/home/index.html.erb
<table>
  <thead>
    <tr>
      <th>Articles</th>
      <th>Users</th>
      <th>Comments</th>
    </tr>
  </thead>

  <tbody>
   <td><button><%= link_to 'Articles', articles_path %></button> </td>
   <td><button><%= link_to 'Users', user_profiles_path %></button> </td>
   <td><button><%= link_to 'Comments', comments_path %></button> </td>
  </tbody>
</table>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Test App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user_profiles/edit.html.erb
<%= form_with scope: :user_profile, url: update_user_profile_path(@user_profile.id), method: :put, local: true do |f| %>

<p>
  <% if @user_profile.errors.any? %>
    <ul>
      <% @user_profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</p>

<p>
  <%= f.label :fullname %><br/>
  <%= f.text_field :fullname %>
</p>

<p>
  <%= f.label :username %><br/>
  <%= f.text_field :username %>
</p>

<p>
  <%= f.label :password %><br/>
  <%= f.password_field :password %>
</p>

<p>
  <%= f.label :email %><br/>
  <%= f.text_field :email %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/user_profiles/index.html.erb
<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Username</th>
      <th>Password</th>
      <th>Email</th>
      <th>Details</th>
      <th>Edit</th>
      <th>Delete</th>
      <th><%= link_to 'New User', new_user_profiles_path  %></th>
    </tr>
  </thead>

  <tbody>
    <% @user_profiles.each do |user_profile| %>
      <tr>
        <td><%= user_profile.fullname %> </td>
        <td><%= user_profile.username %> </td>
        <td><%= user_profile.password_digest %> </td>
        <td><%= user_profile.email %> </td>
        <td><%= link_to 'Show', user_profile_path(user_profile.id) %> </td>
        <td><%= link_to 'Edit', edit_user_profile_path(user_profile.id) %> </td>
        <td><%= button_to 'Delete', delete_user_profile_path(user_profile.id), method: :delete %> </td>
      </tr>
    <% end %>
  </tbody>
</table>


app/views/user_profiles/new.html.erb
<%= form_with scope: :user_profile, url: create_user_profile_path, local: true do |f| %>

<p>
  <% if @user_profile.errors.any? %>
    <ul>
      <% @user_profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</p>

<p>
  <%= f.label :fullname %><br/>
  <%= f.text_field :fullname %>
</p>

<p>
  <%= f.label :username %><br/>
  <%= f.text_field :username %>
</p>

<p>
  <%= f.label :password %><br/>
  <%= f.password_field :password %>
</p>

<p>
  <%= f.label :email %><br/>
  <%= f.text_field :email %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/user_profiles/show.html.erb
<table>
  <thead>
    <tr>
      <th>Full Name</th>
      <th>Username</th>
      <th>Password</th>
      <th>Email</th>
    </tr>
  </thead>

  <tbody>
      <tr>  
        <td><%= @user_profile.fullname %> </td>
        <td><%= @user_profile.username %> </td>
        <td><%= @user_profile.password_digest %> </td>
        <td><%= @user_profile.email %> </td>
      </tr>
  </tbody>
</table>
